services:
  webserv:
    container_name: WebservSIR
    build:
      context: .
      dockerfile: Dockerfile
      network: host # needed for some systems
    ports:
      - "8080:8080"
    volumes:
      - ./www/:/usr/webserv/www/
      - ./config_files/default.conf:/usr/webserv/config_files/default.conf
    restart: always
