services:
  webserv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./www/:/usr/webserv/www/
      - ./config_files/local.conf:/usr/webserv/config_files/local.conf
    restart: always
  
  nginx:
    image: nginx:latest
    ports:
      - "8180:8180"
      - "8181:8181"
    volumes:
      - ./config_files/nginx.conf:/etc/nginx/nginx.conf
      - ./www/:/var/www/
    restart: always
